# Generated by Django 4.2.6 on 2024-04-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternSHip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstr_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=200)),
                ('street_address2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=254)),
                ('alt_phoneNo', models.CharField(max_length=100)),
                ('selected_course', models.CharField(max_length=100)),
                ('referred_HR', models.CharField(max_length=100)),
                ('addition_comments', models.TextField()),
                ('profile_img', models.FileField(upload_to='uploads/')),
                ('transaction_ID', models.CharField(max_length=100)),
            ],
        ),
    ]
