# Generated by Django 4.2.6 on 2024-04-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationForm',
            new_name='RegistrationFormStudent',
        ),
    ]
