# Generated by Django 4.2.6 on 2024-04-15 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_studentregister_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregister',
            name='phoneNo',
        ),
        migrations.AddField(
            model_name='studentregister',
            name='gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
