# Generated by Django 4.2.6 on 2024-04-15 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_studentregister_phoneno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregister',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
