# Generated by Django 5.0.6 on 2024-07-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='looking_for',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
