# Generated by Django 5.0.6 on 2024-07-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_enquiry_country_alter_enquiry_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('looking_for', models.CharField(max_length=50)),
                ('agree_terms', models.BooleanField()),
                ('course_name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
