# Generated by Django 5.0.6 on 2024-07-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_coursesforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesforms',
            name='course_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
