# Generated by Django 5.0.6 on 2024-08-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregister',
            old_name='addition_comments',
            new_name='additional_comments',
        ),
        migrations.RenameField(
            model_name='studentregister',
            old_name='firstr_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
