# Generated by Django 5.0.6 on 2024-08-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
